configMapGenerator:
  - name: redis-config
    files:
      - redis.conf
generatorOptions:
  disableNameSuffixHash: true
resources:
  - redis.statefulset.yaml
  - redis.service.yaml
images:
  - name: redis
    newName: mirror.gcr.io/library/redis
    newTag: alpine
