---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gnomad-reads
  labels:
    component: gnomad-reads
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gnomad-reads
  template:
    metadata:
      labels:
        name: gnomad-reads
    spec:
      containers:
        - name: web
          image: gnomad-reads-server
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: '50m'
              memory: '4Gi'
            limits:
              cpu: '100m'
              memory: '4Gi'
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          volumeMounts:
            - name: readviz
              mountPath: /readviz
        - name: app
          image: gnomad-reads-api
          env:
            - name: PORT
              value: '8000'
            - name: TRUST_PROXY
              value: '3'
            - name: DATASETS
              value: gnomad_r2_1,exac
            - name: GNOMAD_R2_1_EXOMES_READS_DIRECTORY
              value: /readviz/datasets/gnomad_r2/combined_bams_exomes/combined_bams
            - name: GNOMAD_R2_1_EXOMES_PUBLIC_PATH
              value: /reads/gnomad_r2_1/exomes
            - name: GNOMAD_R2_1_GENOMES_READS_DIRECTORY
              value: /readviz/datasets/gnomad_r2/combined_bams_genomes/combined_bams
            - name: GNOMAD_R2_1_GENOMES_PUBLIC_PATH
              value: /reads/gnomad_r2_1/genomes
            - name: EXAC_EXOMES_READS_DIRECTORY
              value: /readviz/datasets/exac/combined_bams_v3
            - name: EXAC_EXOMES_PUBLIC_PATH
              value: /reads/exac/exomes
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: '50m'
              memory: '128Mi'
            limits:
              cpu: '100m'
              memory: '256Mi'
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          volumeMounts:
            - name: readviz
              mountPath: /readviz
      nodeSelector:
        cloud.google.com/gke-nodepool: 'default-pool'
      volumes:
        - name: readviz
          gcePersistentDisk:
            fsType: ext4
            pdName: readviz-data
            readOnly: true
