apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./api.deployment.yaml
  - ./api.service.yaml
  - ./browser.deployment.yaml
vars:
  - name: API_SERVICE
    objref:
      kind: Service
      name: gnomad-api
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
