name: CI
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: install
      run: yarn install --frozen-lockfile --non-interactive --no-progress
    - name: eslint
      run: yarn run lint:js
    - name: stylelint
      run: yarn run lint:css
    - name: test
      run: yarn test
